#!/usr/bin/env groovy

def call(Map config = [:]) {
    script {
        echo "🔒 Starting Secret Leak Scanning with Gitleaks..."

        // 1. Install gitleaks if not already installed
        if (sh(script: "command -v gitleaks >/dev/null 2>&1", returnStatus: true) != 0) {
            echo "📦 Installing Gitleaks..."
            sh '''
                curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-arm64 \
                  -o /usr/local/bin gitleaks
                chmod +x /usr/local/bin/gitleaks
            '''
            echo "📦 Gitleaks installed"
        } else {
            echo "⚡ Gitleaks already installed"
        }

        // 2. Run gitleaks scan
        def reportFile = "gitleaks-report.json"
        def exitCode = sh(
            script: "gitleaks detect --source . --report-format json --report-path ${reportFile}",
            returnStatus: true
        )

        // 3. Archive report for Jenkins
        archiveArtifacts artifacts: reportFile, allowEmptyArchive: true

        if (fileExists(reportFile)) {
            echo "📊 Secret scan completed. Report saved: ${reportFile}"
        } else {
            echo "⚠️  No report generated by Gitleaks"
        }

        // 4. Handle results
        if (exitCode != 0) {
            if (config.allowFailure) {
                echo "❗ Secrets found, but continuing pipeline (allowFailure = true)."
                currentBuild.result = 'UNSTABLE'
            } else {
                error "❌ Secret leaks detected! Check ${reportFile} for details."
            }
        } else {
            echo "✅ No secrets detected."
        }
    }
}
